// Code generated by github.com/dashotv/golem. DO NOT EDIT.

export interface File {
  id?: string;
  created_at?: string;
  updated_at?: string;

  type?: string;
  path?: string;
  size?: number;
  modified_at?: number;
  medium_id?: string;
}
export interface Library {
  id?: string;
  created_at?: string;
  updated_at?: string;

  name?: string;
  path?: string;
  library_type_id?: string;
  library_template_id?: string;
  library_type?: LibraryType;
  library_template?: LibraryTemplate;
}
export interface LibraryTemplate {
  id?: string;
  created_at?: string;
  updated_at?: string;

  name?: string;
  template?: string;
}
export interface LibraryType {
  id?: string;
  created_at?: string;
  updated_at?: string;

  name?: string;
}
